# Lab 01 - Getting Started

Name: Andrew Hawk  
Class: CSCI 349 - Intro to Data Mining  
Semester: 2020SP  
Instructor: Brain King  

### 2. Did you read the syllabus? All of it? Do you agree to abide by the cheating rules? Write a sentence clearly indicating your commitment to not cheating.  



I will not cheat in this course. I understand that failure to adhere to the Bucknell University Honor Code will result in immediate failure of the course.

### 3. What are you hoping to get out of this course?  


I want to gain a solid understanding of the main Python packages used for data science. I would like to have the ability to use these packages successfully for a job and/or personal projects. 

### 4. Print the Python version (available in sys package)

In [5]:
import sys
print(sys.version)

3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]


### 5. Create a Python list of 10000 random integers in the range 1 to 100, using the random package. Name the list x_list.

In [6]:
import random
x_list = list()
for i in range(10000):
    x_list.append(random.randrange(1,101))

### 6. What is the minimum value of x_list? What is the max value? What is the mode?

In [7]:
from statistics import mode

print("The minimum value of x_list is: {}.".format(min(x_list)))
print("The maximum value of x_list is: {}.".format(max(x_list)))
print("The mode of x_list is: {}.".format(mode(x_list)))

The minimum value of x_list is: 1.
The maximum value of x_list is: 100.
The mode of x_list is: 69.


### 7. Write a function to take a list of numbers as a parameter, and return the average of the list. Then, use your function to report the average value of x_list, printed as a float with 2 places of precision.

In [8]:
from statistics import mean
def averageOfList(inList):
    return mean(inList)

In [9]:
print("The average value of x_list is: {:.2f}.".format(averageOfList(x_list)))

The average value of x_list is: 50.68.


### 8. Create a list called x_hist that represents a histogram, i.e. a distribution of the numerical data, of x_list. Each entry in x_hist should contain the range of data in widths of 10. So, x_hist[0] represents the frequency of numbers between 1-10, x_hist[1] is the frequency of numbers between 11-20, and soon. Be sure to print x_hist at the end.

In [10]:
import math

x_hist = [0,0,0,0,0,0,0,0,0,0]

for i in x_list:
    if (i == 0):
        x_hist[0] += 1;
    else:
        x_hist[math.ceil(i/10)-1] += 1;
        
print(x_hist)

[990, 1001, 1045, 929, 1042, 963, 1016, 1002, 970, 1042]


### 9. What is numpy? What are its strengths? Does it have any weaknesses?

NumPy is a Python library that provides a multidimensional array object, various derived objects, and an assortment of routines for fast operations on arrays. A strength of NumPy is that its operations on arrays are executed much more efficiently and with less code than Python's built-in sequences. Another strength of NumPy is that it's array objects have a smaller memory consumption than Python lists. Also, many other important data science packages such as scikit-learn and pandas use NumPy arrays. A weakness is that a NumPy array is homoegenous which may provide limitations to a given project. 



### 10. Import the numpy package as np and print the numpy version

In [11]:
import numpy as np
print(np.__version__)


1.18.1


### 11. What is the primary object type in numpy? Can it store data of different types? Discuss.  

The primary object type in numpy is the homogeneous multidimensional array. Since the array is homogenous, the data is all stored as the same type.  

### 12. Discuss the types of data available in numpy. You need not list every type. Just generalize, and discuss how the type system is different than the built-in types int and float in Python.  

There is a larger variety of available types available in NumPy compared to the built-in types in Python. Since NumPy is built in C, many of the C data types are availble in NumPy. For example, rather than a regular int type in Python, NumPy has shorts, ints, longs and long longs that can be signed or unsigned to represent integers. 


### 13. Create a numpy array from x_list. Reassign it as x_list. Show the contents.

In [51]:
x_list = np.array(x_list)
print(x_list)

[63. 95. 30. ... 76. 78. 10.]


### 14. Redo the previous exercise, but set the data type of each value to 'float32'

In [55]:
np.array(x_list, dtype=np.float32)
print(x_list)

[63. 95. 30. ... 76. 78. 10.]


### 15. Create a length 10 integer array filled with zeros

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 16. Create a float array of 3 rows and 4 columns, all initialized to one.

In [45]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 17. Create and array of 20 values, evenly spaced between 1 and 3 (HINT - look at np.linspace)

In [22]:
np.linspace(1, 3, 20)

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

### 18. Set the numpy random seed to the value 12345, then create a 10 x 5 array of random integers on the interval [10, 20)

In [38]:
np.random.seed(12345)
np.floor(10*np.random.random((10,5))+10)

array([[19., 13., 11., 12., 15.],
       [15., 19., 16., 17., 16.],
       [17., 19., 10., 11., 12.],
       [16., 18., 18., 19., 17.],
       [16., 17., 14., 13., 14.],
       [17., 19., 16., 17., 11.],
       [10., 18., 19., 10., 14.],
       [15., 15., 10., 18., 17.],
       [18., 15., 18., 10., 12.],
       [12., 14., 14., 17., 11.]])