# Lab 02 - numpy

Name: Andrew Hawk  
Class: CSCI 349 - Intro to Data Mining  
Semester: 2020SP  
Instructor: Brain King  

In [2]:
# Setting things up
import sys
import numpy as np

### 1. Create an 52500 x 75 matrix of zeros, stored as X. Then, print out the shape of the matrix, the base data type, the individual item size in the array, and the total size of the array in bytes (as an integer). Also, print out the total size in megabytes with 3 places of significance.

In [3]:
X = np.zeros((52500,75))
print("Shape:", X.shape)
print("Base data type:", X.dtype)
print("Individual item size:", X.itemsize)
print("Total size in bytes:", X.size*X.itemsize)
print("Total size in megabytes:{:.3f}".format((X.size*X.itemsize)/1000000))


Shape: (52500, 75)
Base data type: float64
Individual item size: 8
Total size in bytes: 31500000
Total size in megabytes:31.500


### 2. Resize X to have the same number of elements, but with 100 rows. Show the shape. Show the number of bytes (which should be the same as the previous answer)

In [4]:
X = X.reshape(100,-1) # -1 means that row dimension is automatically calculated
print("Shape:", X.shape)
print("Total size in bytes:", X.size*X.itemsize)

Shape: (100, 39375)
Total size in bytes: 31500000


### 3. Redo #1, but use a base datatype of 16-bit integers.

In [5]:
X = np.zeros((52500,75), dtype=np.int16)
print("Shape:", X.shape)
print("Base data type:", X.dtype)
print("Individual item size:", X.itemsize)
print("Total size in bytes:", X.size*X.itemsize)
print("Total size in megabytes:{:.3f}".format((X.size*X.itemsize)/1000000))

Shape: (52500, 75)
Base data type: int16
Individual item size: 2
Total size in bytes: 7875000
Total size in megabytes:7.875


### 4. How many dimensions does X have? Answer using the appropriate property of np.ndarray objects.

In [6]:
print("Number of dimensions:", X.ndim)

Number of dimensions: 2


### 5. Enter the following list in your cell: 
### str_nums = ['2.14', '-9.3', '42']
### Convert this to a numpy array named X. What is the base type? Show the contents of X. Then, convert X to an array of single precision floating point numbers. (HINT: use astype). Show X again. 

In [7]:
str_nums = ['2.14', '-9.3', '42']
X = np.array(str_nums)
print("Base data type:", X.dtype)
print("Contents:", X)
X = X.astype(np.float32)
print("Contents:", X)

Base data type: <U4
Contents: ['2.14' '-9.3' '42']
Contents: [ 2.14 -9.3  42.  ]


### Let's assume you have two week's worth of quiz scores. Quizzes are out of 10 points, and are given every day. Enter the following in your cell:
### days = ["Mon","Tue","Wed","Thu","Fri"] <br/> scores_1 = [9.5, 8.75, 8, 10, 7.75] <br/>scores_2 = [9, 8, 10, 8.75, 7.25]

### 6. Copy the three definitions above for days, scores_1, and scores_2. Create a numpy array called scores, that has scores_1 as the first row and scores_2 as the second row, using np.concatenate. Then, change days into a np.array from the list days. Show the contents of scores and days, and output their shape.

In [34]:
days = ["Mon","Tue","Wed","Thu","Fri"]
scores_1 = [[9.5, 8.75, 8, 10, 7.75]]
scores_2 = [[9, 8, 10, 8.75, 7.25]]

scores = np.concatenate([scores_1,scores_2], axis=0)
print("Scores: ",scores)
print("Scores shape:", scores.shape)
days = np.array(days)
print("Days:",days)
print("Days shape:", days.shape)

Scores:  [[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]]
Scores shape: (2, 5)
Days: ['Mon' 'Tue' 'Wed' 'Thu' 'Fri']
Days shape: (5,)


### 7. Repeat the previous problem with the creation of scores from scores_1 and scores_2, but repeat it with np.vstack. The array should be identical. 

In [9]:
scores = np.vstack((scores_1, scores_2))
print("Scores:")
print(scores)

Scores:
[[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]]


### 8. Compare the result of the expression days == "Fri" if the variable days was a Python list as entered above, vs. days being a numpy array. What is the difference in the result? In general, how does numpy deal with standard comparison operators?

For a python list, a single boolean value is returned. The value is true if the value on the right side of the "==" is a list equivalent to that on the left side of the "==". So, the result of days == "Fri" for a python list is 'False'. For a numpy array, an array of boolean values is returned. Each value in days is compared. The result of days == "Fri" is [False. False, False, False, True]. numpy does an evaluates each element with the comparison operator.

### 9. Select the scores that fell on Monday. 

In [10]:
scores[:, days == "Mon"]

array([[9.5],
       [9. ]])

### 10. Select all of the scores that are NOT on Monday (Hint – look up the ~ operator)

In [11]:
scores[:, ~(days == "Mon")]

array([[ 8.75,  8.  , 10.  ,  7.75],
       [ 8.  , 10.  ,  8.75,  7.25]])

### 11. Select the scores that were on Tuesday or Thursday

In [12]:
# Reference: https://stackoverflow.com/questions/10062954/valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous
scores[:, (days == "Tue") | (days == "Thu")]

array([[ 8.75, 10.  ],
       [ 8.  ,  8.75]])

### 12. Show the minimum and maximum scores for the entire array of scores

In [13]:
print("Min:",np.min(scores))
print("Max:",np.max(scores))

Min: 7.25
Max: 10.0


### 13. Show the minimum scores for each week as a new array. The result should have the same dimensions (hint– use the keepdims parameter).

In [14]:
np.amin(scores, axis=1, keepdims=True)



array([[7.75],
       [7.25]])

### 14. Report the day that the maximum score occurred each week. (HINT: use argmax and use that result to index days.)

In [15]:
maxDays = np.argmax(scores, axis=1)
print("Max score of first week occured on a", days[maxDays[0]])
print("Max score of second week occured on a", days[maxDays[1]])

Max score of first week occured on a Thu
Max score of second week occured on a Wed


### 15. Report the mean of the scores of each week

In [16]:
np.mean(scores, axis = 1)

array([8.8, 8.6])

### 16. Suppose the lowest score was dropped from each week. Report the mean of each week, but without the minimum score for that week.

In [17]:
np.mean(np.delete(scores, np.argmin(scores,axis=1), axis = 1), axis = 1)


array([9.0625, 8.9375])

### 17. Convert the scores to fall on a scale from 0-100 instead of 0-10. Show the result.

In [18]:
np.multiply(scores,10)

array([[ 95. ,  87.5,  80. , 100. ,  77.5],
       [ 90. ,  80. , 100. ,  87.5,  72.5]])

In [19]:
np.random.seed(1234)
X = np.random.randint(1,100,50).reshape((10,5))
X

array([[48, 84, 39, 54, 77],
       [25, 16, 50, 24, 27],
       [31, 44, 31, 27, 59],
       [93, 70, 81, 74, 48],
       [51, 77, 38, 35, 39],
       [68, 12,  1, 76, 81],
       [ 4,  3, 20, 13, 66],
       [76, 82, 15, 72, 61],
       [47, 29, 82, 88, 14],
       [97, 13, 70, 96, 32]])

### 18. Select the first row of X

In [20]:
X[0]

array([48, 84, 39, 54, 77])

### 19. Select the last column of X

In [21]:
X[:, [4]]

array([[77],
       [27],
       [59],
       [48],
       [39],
       [81],
       [66],
       [61],
       [14],
       [32]])

### 20. Select the first AND last column of X

In [22]:
X[:, [0,4]]

array([[48, 77],
       [25, 27],
       [31, 59],
       [93, 48],
       [51, 39],
       [68, 81],
       [ 4, 66],
       [76, 61],
       [47, 14],
       [97, 32]])

### 21. Select every other row of X

In [23]:
X[0::2,:]

array([[48, 84, 39, 54, 77],
       [31, 44, 31, 27, 59],
       [51, 77, 38, 35, 39],
       [ 4,  3, 20, 13, 66],
       [47, 29, 82, 88, 14]])

### 22. Show the transpose of X, but don't change X itself

In [24]:
X.T

array([[48, 25, 31, 93, 51, 68,  4, 76, 47, 97],
       [84, 16, 44, 70, 77, 12,  3, 82, 29, 13],
       [39, 50, 31, 81, 38,  1, 20, 15, 82, 70],
       [54, 24, 27, 74, 35, 76, 13, 72, 88, 96],
       [77, 27, 59, 48, 39, 81, 66, 61, 14, 32]])

### 23. Select the first column of X and set the result to Y

In [25]:
Y = X[:, 0]
print(Y)

[48 25 31 93 51 68  4 76 47 97]


### 24. Increment the first value of Y, then show the corresponding value of X. Did both values in X and Y change? THIS IS AN IMPORTANT OBSERVATION WHEN DEALING WITH SELECTING DATA!

In [26]:
Y[0] += 1
print(X[0,0]) # both values in X and Y changed!

49


### 25. Repeat exercise 23, but ensure that Y is assigned a copy of the selected data. Increment the first value of Y again and ensure that the corresponding value of X did not change.

In [27]:
Y = X[:,0].copy()
Y[0] += 1
print(Y[0])
print(X[0,0])

50
49


### 26. Create an array that contains the sequence of numbers 0, 0.1, 0.2, ... 9.8, 9.9 using arange, as a 10x10 matrix, stored as X.

In [28]:
X = np.arange(0, 10, 0.1).reshape((10,10))
print(X)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]
 [6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9]
 [7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]
 [8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9]
 [9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]]


### 27. Set the RNG seed to 1234. Then create an array X of 100 uniformly distributed numbers, with all values between 1.0 and 10.0. Then, show the mean, the median, the minimum and maximum values of X.

In [29]:
np.random.seed(1234)
X = 9*np.random.random((10,10))+1
print("Mean:", np.mean(X))
print("Median:", np.median(X))
print("Min:", np.min(X))
print("Max:", np.max(X))


Mean: 5.665266170909222
Median: 5.827284349552116
Min: 1.0558766492841647
Max: 9.928733195695253


### 28. Define what is meant by a normal distribution. What are the parameters of a normal distribution?

Normal distribution (also known as Gaussian distribution) is a probability distribution that is symmetric about the mean. A normal distribution appears as a bell curve. A normal distribution has two parameters: the mean and the standard distribution.

### 29. In simple terms, using a normal distribution, what does the Law of Large Numbers tell us?

The Law tells us that as the number of random events increases, the observed mean of the events will converge to the mean of the normal distribution.



### 30. Write a function called test_normal_dist. The purpose of this function is to evaluate the law of large numbers. It should have four parameters:

In [30]:
def test_normal_dist(mu, sd, vec_length, num_trials):
    np.random.seed(1234)
    deviation_total = np.float64()
    for i in range(num_trials):
        normDisNums = np.random.normal(loc=mu, scale=sd, size=vec_length)
        deviation_total += (np.absolute(np.mean(normDisNums)) - mu)
    return deviation_total/num_trials
        

### 31. Use test_normal_dist to obtain the deviation for vector lengths of 10, 100, 1000, 10000, and 100000. Use a fixed number of trials of 100 for each experiment. Report the results as a numpy array with two dimensions. the first being the vector length, and the second being the average deviation resulting from your test_normal_dist function.

In [31]:
np.set_printoptions(suppress=True) # Avoid printing out in scientific notation
dist_results = np.zeros((5,2))
vec_lengths = np.array([10, 100, 1000, 10000, 100000])
dist_results[:,0] = vec_lengths;
for i in range(0,5):
    dist_results[i,1] = test_normal_dist(0, 2, vec_lengths[i], 100).round(4)
print(dist_results)

[[    10.          0.4772]
 [   100.          0.1619]
 [  1000.          0.0446]
 [ 10000.          0.0159]
 [100000.          0.0049]]
